### ISSUE TITLE
Update doc to emphasize starting endpoint in the right virtual env

### ISSUE THREAD

**Issue by Zilinghan** [APPFL/APPFLx-doc#3]
As titled.

**Comment by madduri** [comment]
Also, I think the title of the menu should be Documentation instead of Document.


--
Ravi K Madduri
Scientist, Data Science and Learning, Argonne National Laboratory
Senior Scientist,  University of Chicago Consortium for Advanced Science and Engineering (UChicago CASE)
@madduri


On 6/15/23, 12:58 PM, "Zilinghan Li" ***@***.***> wrote:


As titled.

**Comment by Zilinghan** [comment]
Done, check the changes:
https://appflx.link/
https://ppflaas.readthedocs.io/en/latest/installation/index.html
